### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by v1rtl** [vimlet/bundl#1]
Bundl would be nicer to use with some sort of plugins, like `bundl-plugin-babel`:

```js
const babel = require('bundl-plugin-babel')

module.exports => {
// some config
  use: babel
}
```

I can make a PR with some plugins and put them into `plugins` directory

**Comment by lethevimlet** [comment]
Plugins are supported :smile: I'm updating the doc to show how they can be done. 

Also, I uploaded a working example for you for babel plugin, I guess this is not Bundl problem. 

run on the root directory:
```
npm install
npx bundl
```
[bundl-examples.zip](https://github.com/vimlet/bundl/files/3471928/bundl-examples.zip)

But i'll have a look at your issue #2 code.

**Comment by lethevimlet** [comment]
Totally up for the PR plugins BTW : )
I'm closing this issue since I believe it's solved. Feel free to re-open it if needed.
