### ISSUE TITLE
Simple build produces a lot of empty files

### ISSUE THREAD

**Issue by v1rtl** [vimlet/bundl#3]
This config generates some empty files in root folder. I guess it is a bug

**bundl.config.js**

```js
const babel = require('../../forks/bundl/plugins/bundl-plugin-babel/index') 

module.exports = {
  output: 'build/bundle.js', /* {
      use: entry => babel(entry, {
        presets: [require('@babel/preset-env')]
      })
    }, */
    input: 'src/**.js'
  }
```

Terminal output:

```
➜ npx @vimlet/bundl
Build started...
-> 1
-> 0
-> 3
-> 6
-> 4
-> 2
-> 5
-> 7
-> 8
-> 9
-> 11
-> 10
-> 14
-> 13
-> 12
Build completed at: 06/08/2019/14:12:13
```

![image](https://user-images.githubusercontent.com/35937217/62535546-59828380-b854-11e9-8501-1feab79c9ae2.png)

**Comment by jesusvimlet** [comment]
It is a bug indeed, it should throw an error because the output key has to be an object.
`module.exports = {
output:{
'build/bundle.js':'src/**.js'
}`
Thanks, it will be fixed soon.

**Comment by lethevimlet** [comment]
Issue #2  related, you need to structure the config with the input being a property of an output key. 
```
const babel = require('../../forks/bundl/plugins/bundl-plugin-babel/index') 

module.exports = {
  output: {
    'build/bundle.js': {
      use: entry => babel(entry, {
        presets: [require('@babel/preset-env')]
      }),
      input: {
        'src/**.js': true
      }
    }
  }
};
```

**Comment by lethevimlet** [comment]
I'm closing this issue since I believe it's solved. Feel free to re-open it if needed.

**Comment by v1rtl** [comment]
@lethevimpet at least it should drop an error of wrong config, like `Error: config is not set properly <error message>`

**Comment by lethevimlet** [comment]
Agree, @jesusvimlet is working on it, thanks @talentlessguy
